import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Favicon from '../public/images/logo.svg';
import {Providers} from "./providers";

const inter  = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FindDelish",
  description: "Generated by create next app",
  icons: [{ rel: 'icon', url: '/images/favicon.png' }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    //   <body className={`${inter.className} dark:bg-gray-900` }>{children}</body>
    // </html>
    <html lang="en" className='dark'>
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
