import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/Providers";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: "FindDelish",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/images/favicon.png" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-gray-900`}>
        <Providers>
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
