import Image from "next/image";
import Link from "next/link";
import React from "react";
import Head from "next/head";
import { Metadata } from "next/types";
import { Input } from "@nextui-org/react";
export const metadata: Metadata = {
  title: "Register",
  description: "Generated by create next app",
};
const Page = () => {
  return (
    <div className="flex w-screen flex-wrap text-slate-800">
      <Head>
        <title>My page title</title>
      </Head>
      <div className="relative hidden h-screen select-none  md:flex md:w-1/2">
        <Image
          src={"/images/register.webp"}
          height={300}
          width={200}
          alt="background"
          className="h-full w-full object-cover"
        />
      </div>
      <div className="flex w-full flex-col md:w-1/2">
        <div className="flex justify-center pt-12 md:justify-start md:pl-12">
          <Link href={"/"}>
            <Image
              src={"/images/logo.svg"}
              height={200}
              width={200}
              alt="logo"
              className="h-10"
            />
          </Link>
        </div>
        <div className="my-auto mx-auto flex flex-col justify-center px-6 pt-8 md:justify-start lg:w-[28rem]">
          <p className="text-center text-3xl font-bold md:text-left md:leading-tight">
            Create your free account
          </p>
          <p className="mt-6 text-center font-medium md:text-left">
            Already using FindDelish? {" "}
            <Link
              href="/auth/login"
              className="whitespace-nowrap font-semibold text-primary"
            >
              Login here
            </Link>
          </p>
          <form className="flex flex-col items-stretch pt-3 md:pt-8">
          <Input
                type="email"
                variant={"bordered"}
                label="Email"
                required
                name="email"
                radius="sm"
                labelPlacement="inside"
              />
            
            <div className="flex flex-col pt-4">
              <div className="relative flex overflow-hidden rounded-md border-2 transition focus-within:border-blue-600">
                <input
                  type="email"
                  id="login-email"
                  className="w-full flex-shrink appearance-none border-gray-300 bg-white py-2 px-4 text-base text-gray-700 placeholder-gray-400 focus:outline-none"
                  placeholder="Email"
                />
              </div>
            </div>
            <div className="mb-4 flex flex-col pt-4">
              <div className="relative flex overflow-hidden rounded-md border-2 transition focus-within:border-blue-600">
                <input
                  type="password"
                  id="login-password"
                  className="w-full flex-shrink appearance-none border-gray-300 bg-white py-2 px-4 text-base text-gray-700 placeholder-gray-400 focus:outline-none"
                  placeholder="Password (minimum 8 characters)"
                />
              </div>
            </div>
            <button
              type="submit"
              className="mt-6 rounded-lg bg-primary px-4 py-2 text-center text-base font-semibold text-white shadow-md outline-none ring-blue-500 ring-offset-2 transition hover:bg-blue-700 focus:ring-2 md:w-32"
            >
              Sign in
            </button>
          </form>
        </div>
      </div>
    </div>
  );
};

export default Page;
